name: 'Branch Publisher'
description: 'GitHub Action for Branch Publish'
author: 'Lorenzo Feng <lorenzo.feng@njust.edu.cn>'
branding:
  icon: 'cloud'
  color: 'blue'
inputs:
  user:
    description: 'Username for git push'
    required: true
  token:
    description: 'Personal Access Token for git push'
    required: true
  repo:
    description: 'Repository path'
    required: true
  branch:
    description: 'Branch name'
    required: false
    default: "pages"
  folder:
    description: 'Dist to publish'
    required: false
    default: "dist"
  github_domain:
    description: 'Domain of git'
    required: false
    default: "github.com"
runs:
  using: 'docker'
  image: 'Dockerfile'
